INSERT INTO Contributor (CID, Name)
VALUES
    ('C001', 'Paul McCartney'),
    ('C002', 'John Lennon'),
    ('C003', 'George Harrison'),
    ('C004', 'Ringo Starr'),
    ('C005', 'Freddie Mercury'),
    ('C006', 'Brian May'),
    ('C007', 'Roger Taylor'),
    ('C008', 'Robert Plant'),
    ('C009', 'Jimmy Page'),
    ('C010', 'John Paul Jones'),
    ('C011', 'John Deacon'),
    ('C012', 'Robert Smith'),
    ('C013', 'Simon Gallup'),
    ('C014', 'Roger Waters'),
    ('C015', 'David Gilmour'),
    ('C016', 'Syd Barrett'),
    ('C017', 'Roger Waters'),
    ('C018', 'Nick Mason'),
    ('C019', 'David Bowie'),
    ('C020', 'Mick Jagger'),
    ('C021', 'Keith Richards'),
    ('C022', 'Charlie Watts'),
    ('C023', 'Ronnie Wood'),
    ('C024', 'Freddy Mercury'),
    ('C025', 'Roger Taylor'),
    ('C026', 'John Deacon'),
    ('C027', 'Brian May'),
    ('C028', 'Robert Plant'),
    ('C029', 'John Paul Jones'),
    ('C030', 'Jimmy Page');
