INSERT INTO Song (SID, Name, Artist, KaraokeFileID, Version)
VALUES
    ('S001', 'Yesterday', 'The Beatles', 'KFI001', 'Original'),
    ('S002', 'Bohemian Rhapsody', 'Queen', 'KFI002', 'Original'),
    ('S003', 'Stairway to Heaven', 'Led Zeppelin', 'KFI003', 'Original'),
    ('S004', 'Billie Jean', 'Michael Jackson', 'KFI004', 'Original'),
    ('S005', 'Imagine', 'John Lennon', 'KFI005', 'Original'),
    ('S006', 'Like a Rolling Stone', 'Bob Dylan', 'KFI006', 'Original'),
    ('S007', 'Smells Like Teen Spirit', 'Nirvana', 'KFI007', 'Original'),
    ('S008', 'Hey Jude', 'The Beatles', 'KFI008', 'Original'),
    ('S009', 'Hotel California', 'Eagles', 'KFI009', 'Original'),
    ('S010', 'Sweet Child O'' Mine', 'Guns N'' Roses', 'KFI010', 'Original'),
    ('S011', 'Born to Run', 'Bruce Springsteen', 'KFI011', 'Original'),
    ('S012', 'Purple Haze', 'Jimi Hendrix', 'KFI012', 'Original'),
    ('S013', 'Livin'' on a Prayer', 'Bon Jovi', 'KFI013', 'Original'),
    ('S014', 'Let It Be', 'The Beatles', 'KFI014', 'Original'),
    ('S015', 'Wonderwall', 'Oasis', 'KFI015', 'Original'),
    ('S016', 'My Generation', 'The Who', 'KFI016', 'Original'),
    ('S017', 'Smoking in the Boys Room', 'Motley Crue', 'KFI017', 'Original'),
    ('S018', 'Every Breath You Take', 'The Police', 'KFI018', 'Original'),
    ('S019', 'Back in Black', 'AC/DC', 'KFI019', 'Original'),
    ('S020', 'Wish You Were Here', 'Pink Floyd', 'KFI020', 'Original'),
    ('S021', 'Under the Bridge', 'Red Hot Chili Peppers', 'KFI021', 'Original'),
    ('S022', 'Dancing Queen', 'ABBA', 'KFI022', 'Original'),
    ('S023', 'Another Brick in the Wall', 'Pink Floyd', 'KFI023', 'Original'),
    ('S024', 'Hotel California', 'Eagles', 'KFI024', 'Original'),
    ('S025', 'Bohemian Rhapsody', 'Queen', 'KFI025', 'Original'),
    ('S026', 'Smells Like Teen Spirit', 'Nirvana', 'KFI026', 'Original'),
    ('S027', 'Stairway to Heaven', 'Led Zeppelin', 'KFI027', 'Original'),
    ('S028', 'Wonderwall', 'Oasis', 'KFI028', 'Original'),
    ('S029', 'Every Breath You Take', 'The Police', 'KFI029', 'Original'),
    ('S030', 'Hey Jude', 'The Beatles', 'KFI030', 'Original');
