INSERT INTO Contributor (CID, CNAME) 
    VALUES('TWX', 'Brittney Spears'),
          ('PENTX', 'Pentatonix'),
          ('KENDRICK', 'Kendrick Lamar'),
          ('PACK', 'PACKGOD'),
          ('GINROOT', 'Ginger Root'),
          ('SAM', 'Sam Ock'),
          ('SKIND', 'SKINDRED'),
          ('CONNOR', 'Connor Price'),
          ('DEV', 'Dev Lemons'),
          ('TEN', 'Tennyson'),
          ('ANO', 'Anomalie'),
          ('SWV', 'SWV'),
          ('MILYE', 'Milye'),
          ('CHANG', 'leon chang'),
          ('BOOYAH', 'the booyah! kids'),
          ('KOOK', 'Jung Kook'),
          ('LAUFEY', 'Laufey'),
          ('BAYLOCK', 'Alan Baylock'),
          ('PEAS', 'Black Eyed Peas'),
          ('GECS', '100 gecs'),
          ('JV&B', 'Joey and Brae'),
          ('JID', 'JID'),
          ('NAHN', 'nahncentz.'),
          ('COLE', 'J. Cole'),
          ('DADOOD', 'DaDood'),
          ('CEE', 'Central Cee'),
          ('WHITE', 'Armani White'),
          ('META', 'Metaroom'),
          ('Lil', 'Lil Dicky');